### ISSUE TITLE
override back button on android?

### ISSUE THREAD

**Issue by xperiafan13-rom** [galadril/Xam.Plugin.SimpleAppIntro#15]

**Comment by AnthonyLatty** [comment]
I am not sure what you are asking, but to override the back button on android place this snippet in the MainActivity.cs class in the Android project.
```
public override void OnBackPressed()
{
    //Code here
}
```

**Comment by galadril** [comment]
As @AnthonyLatty stated, you can do that on the activity, not needed in this library
