### ISSUE TITLE
Not show PositionIndicator

### ISSUE THREAD

**Issue by xcesaralejandro** [galadril/Xam.Plugin.SimpleAppIntro#2]
He estado probando el plugin y me parece genial lo simple que es, pero no logro mostrar la barra indicadora de slide:

`welcomePage.ShowPositionIndicator = true;`

Por cierto, ¿Puedo personalizar el color de fondo de un slide en particular?

**Comment by galadril** [comment]
english please

**Comment by xcesaralejandro** [comment]
I have been testing the plugin and it seems great how simple it is, but I can not show the slide bar (Phone model : Google pixel XL - Android version: 8.1):
`welcomePage.ShowPositionIndicator = true;`
By the way, can I customize the background color of a particular slide?

**Comment by xcesaralejandro** [comment]
Thanks, but the bar that indicates the position of slide is not shown is a bug? or I must instantiate something in special.

![image](https://user-images.githubusercontent.com/24363177/43374748-4591938e-937f-11e8-9e81-50251f7dca2f.png)

Another problem I found, is that hiding the skip button and pressing the side where it should be works the same way.

I leave you some suggestions in case you want to implement them :)

1.- To be able to change the size of the text
2.- To be able to use images for the buttons of skip and done

I would love to help with the implementation of this, but I have just started in Xamarin a couple of days ago :(

**Comment by galadril** [comment]
I'm using TitleStyle and BodyStyle as the styles for the text in the intro. maybe you could do something with style Overriding Global Styles in your app:
https://docs.microsoft.com/nl-nl/xamarin/xamarin-forms/user-interface/styles/xaml/application#overriding-styles
