### ISSUE TITLE
Indicators not showing

### ISSUE THREAD

**Issue by AnthonyLatty** [galadril/Xam.Plugin.SimpleAppIntro#21]
The property `ShowPositionIndicator` when set to `true` does not display indicators at the bottom of slides. Is this a bug?

Version of plugin: 1.0.24
Version of Xamarin.Forms: 4.4.0.991640
Android version: 9.0

**Comment by AnthonyLatty** [comment]
Fixed my issue

**Comment by galadril** [comment]
Wow that was quick. Thanks

Op di 18 feb. 2020 18:43 schreef Marc-Anthony Latty <
notifications@github.com>:

**Comment by aleciatti** [comment]
Sorry i have the same problem in which way can i resolve? I set showPositionIndicator = true but i don't see it. Thanks a lot

**Comment by galadril** [comment]
Please check the sample app. You need the indicator icons on your project
