### ISSUE TITLE
not working on me

### ISSUE THREAD

**Issue by halukmy** [galadril/Xam.Plugin.SimpleAppIntro#27]
![image](https://user-images.githubusercontent.com/2916333/89824490-dc22da80-db5b-11ea-8fbb-0f7a813ba2a0.png)

**Comment by galadril** [comment]
try to install the lottie forms nuget package as well

Op ma 10 aug. 2020 om 21:50 schreef Haluk <notifications@github.com>:

**Comment by halukmy** [comment]
@galadril problem is, if android target 9, this thing not visible, if change to target 10, everythings ok

**Comment by galadril** [comment]
so lottie forms plugin isnt working when you set target 9..?

**Comment by halukmy** [comment]
yeah , i just search some, everybody says that
