### ISSUE TITLE
edittext

### ISSUE THREAD

**Issue by halukmy** [galadril/Xam.Plugin.SimpleAppIntro#28]
can we add  textbox ?

**Comment by galadril** [comment]
You can use custom contentview as a custom slide.. so everything is possible ;)

Even use the IValidate and ISave interface implementations to get triggered for validating the content of the textbox

**Comment by galadril** [comment]
https://github.com/galadril/Xam.Plugin.SimpleAppIntro#custom-contentviews

for more info on custom contentviews
