### ISSUE TITLE
Back button only appears at the end

### ISSUE THREAD

**Issue by MSchlick** [galadril/Xam.Plugin.SimpleAppIntro#32]
Hello,

I activate the back button, but it only appears at the last Slide.
When I slide back, everything will be fine.

**Comment by MSchlick** [comment]
It just does happen, when ShowSkipButton = false and ShowBackButton = true

**Comment by galadril** [comment]
v1.0.35
https://www.nuget.org/packages/Xam.Plugin.SimpleAppIntro/1.0.35
