### ISSUE TITLE
Wrong Horizontal Position of Skip Image

### ISSUE THREAD

**Issue by hlubik** [galadril/Xam.Plugin.SimpleAppIntro#7]
Hi,
in AnimatedSimpleAppIntro.xaml Line 91 you set HorizontalOptions to "EndAnd Expand" but it should be "StartAndExpand".

Thanks.

**Comment by galadril** [comment]
hmm also in the SimpleAppIntro.xaml
Thanks for the notice

**Comment by galadril** [comment]
👍
